"""add_new_column_to_users

Revision ID: 30631c1d73f0
Revises: 861d3bc25194
Create Date: 2026-03-28 18:21:02.820827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30631c1d73f0'
down_revision: Union[str, None] = '861d3bc25194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'wound_records', ['id'])
    op.create_unique_constraint(None, 'wounds', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wounds', type_='unique')
    op.drop_constraint(None, 'wound_records', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
