"""add_updated_at_to_wounds

Revision ID: 66d71c71be52
Revises: 87cf38d6cf55
Create Date: 2026-03-29 17:19:37.044121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d71c71be52'
down_revision: Union[str, None] = '87cf38d6cf55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wounds', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wounds', 'updated_at')
    # ### end Alembic commands ###
