"""add_updated_at_to_records

Revision ID: 8a4fd9a25249
Revises: 27b8332558fd
Create Date: 2026-03-29 17:49:30.827303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4fd9a25249'
down_revision: Union[str, None] = '27b8332558fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wound_records', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wound_records', 'updated_at')
    # ### end Alembic commands ###
