"""add overlay_url

Revision ID: da5cdb9190dc
Revises: 8a4fd9a25249
Create Date: 2026-04-02 11:35:53.214017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5cdb9190dc'
down_revision: Union[str, None] = '8a4fd9a25249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wound_records', sa.Column('overlay_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wound_records', 'overlay_url')
    # ### end Alembic commands ###
